/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: hello.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "hello.pb-c.h"
void   hello_world_msg__init
                     (HelloWorldMsg         *message)
{
  static const HelloWorldMsg init_value = HELLO_WORLD_MSG__INIT;
  *message = init_value;
}
size_t hello_world_msg__get_packed_size
                     (const HelloWorldMsg *message)
{
  assert(message->base.descriptor == &hello_world_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hello_world_msg__pack
                     (const HelloWorldMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hello_world_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hello_world_msg__pack_to_buffer
                     (const HelloWorldMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hello_world_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HelloWorldMsg *
       hello_world_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HelloWorldMsg *)
     protobuf_c_message_unpack (&hello_world_msg__descriptor,
                                allocator, len, data);
}
void   hello_world_msg__free_unpacked
                     (HelloWorldMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hello_world_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hello_world_msg__field_descriptors[1] =
{
  {
    "content",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HelloWorldMsg, content),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hello_world_msg__field_indices_by_name[] = {
  0,   /* field[0] = content */
};
static const ProtobufCIntRange hello_world_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hello_world_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HelloWorldMsg",
  "HelloWorldMsg",
  "HelloWorldMsg",
  "",
  sizeof(HelloWorldMsg),
  1,
  hello_world_msg__field_descriptors,
  hello_world_msg__field_indices_by_name,
  1,  hello_world_msg__number_ranges,
  (ProtobufCMessageInit) hello_world_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
